### ISSUE TITLE
External courses (landing page and node)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#192] opened 2018-03-21 17:49 UTC
There are 4 days in the proposal for this.

# Done criteria
- [x] TWEAK remove card images from landing page
- [x] TWEAK create editor account for Steph
- [ ] ~TWEAK maintain card size (on landing page) - see images below~
- [ ] ~TWEAK Update the button on the landing page to go [here](http://bgs-dev.mrmdev.co.uk/events/external-courses/add-an-external-course)~
- [ ] ~TWEAK confirmation email  to editor@bgs.org.uk and s.slack@bgs.org.uk~ **Done for external events and courses**
- [ ] ~ISSUE 1 Card not showing for anonymous users~
- [ ] ~TWEAK send confirmation of submission email to the event submitter~
- [ ] ~Build and style landing page (no search or filters needed)~
- [ ] ~Course starting soonest should be at the top~
- [ ] ~Build and style node page~
- [ ] ~Build and style form to enable people with account to submit a course with these fields~
- [ ] ~Enable Web Admin to review/edit and publish course~
- [ ] ~Web Admin able to specify date for course to be removed from the site~
- [ ] ~Landing page is linked to from 'External courses' link in the Events section of global nav~
- [ ] Fields for node page: **(Check the order and labels for each field)**
  - ~Course title (maximum characters to be decided)~
  - ~Institution name & website~
  - ~Registration address:~
  - ~Start date (date)~
  - ~Course duration (text)~
  - ~Cost (text)~
  - ~Full time/part time (can be one or both options - maybe a check box?)~
  - ~Residential; non-residential; distance learning (can be one or both options - maybe a check box?)~
  - ~Method of assessment~
  - ~Course overview (text)~
- [ ] For the web form **(Check the order and labels for each field)**
  - ~Course title (maximum characters to be decided)~
  - ~Institution name and website~
  - ~Start date (date)~
  - ~Course duration (text)~
  - ~Cost (text)~
  - ~Full time/part time (can be one or both options - maybe a check box?)~
  - ~Residential; non-residential; distance learning (can be one or both options - maybe a check box?)~
  - ~Registration address:~
  - ~Method of assessment:~
  - ~Course overview (text, 300 words)~ **Limited to 1200 characters**
  -  ~Website where more supporting information may be obtained:~

# Designs & Docs
- [External courses landing page on RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457346043488924)
- [External courses node](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457346043488925)

**Comment by angievanhegan** [comment] 2018-03-21 17:49
@StephMSlack Can you check these done criteria are ok please? Thanks

**Comment by StephMSlack** [comment] 2018-03-22 16:27
@angievanhegan just clarified default view - event happening soonest should be at the top, event further away (in terms of date) should be last.

**Comment by StephMSlack** [comment] 2018-03-22 16:35
@angievanhegan fields for the form below. All fields are mandatory except the reciprocal marketing checkbox. 

Event title (maximum characters to be decided)
Start date 
End date
Venue - specific address inc postcode
Venue - City/Country
Organiser
Information about your event - Free text box, limit to 150 words)
Intended audience - Free text box
Cost 
Weblink or email address for programme and registration
check box - I agree to promote in response a BGS meeting on an equal basis. If the check box is not ticked, we need to show a cost for promoting the event on the site.

**Comment by angievanhegan** [comment] 2018-05-23 17:38
@pipe-manta @russ-manta I've updated the done criteria with the fields from Steph. @russ-manta Do you know about integrating payment for this?

**Comment by StephMSlack** [comment] 2018-05-30 09:33
@angievanhegan could we also add a step at the end sending a confirmation of submission email to the event submitter? Geraint will be supplying the text.

**Comment by angievanhegan** [comment] 2018-05-30 16:03
@russ-manta How much extra work will Steph's request be please? Thanks

**Comment by angievanhegan** [comment] 2018-06-08 19:04
@pipe-manta Can you put a line through all the things that are done?

**Comment by pipe-manta** [comment] 2018-06-11 15:47
@angievanhegan Done!

**Comment by angievanhegan** [comment] 2018-06-11 16:33
@pipe-manta There's one more tweak from Steph. Is this something you can do?

**Comment by pipe-manta** [comment] 2018-06-12 09:06
Hi @StephMSlack and @angievanhegan, for external free events, paid events and courses, we have this steps for the process:

Free events and courses:
1. After submission: the web editor and submitter receive an email with the notification of the new submission. Status: Not processed.
2. After reviewing the content, the status can be changed to "Approved, payment not required" and the content will be published automatically. The submitter receives an email with the confirmation.

Paid events:
1. After submission:  the web editor and submitter receive an email with the notification of the new submission. Status: Not processed.
2. After reviewing the content, the status can be changed to "Reviewed, payment requested" and the submitter receives an email with the payment information/link to proceed.
2. After receive the payment, the status can be changed to "Approved, payment completed" and the content will be published automatically. The submitter receives an email with the confirmation.

We just need to know on which email would you like to receive the confirmation of the new submissions.

**Comment by angievanhegan** [comment] 2018-06-13 13:32
@StephMSlack This is ready to review. Can you also confirm which email the submission confirmation for events should go to? Thanks

**Comment by StephMSlack** [comment] 2018-06-13 15:48
The confirmation email should go to Recia (editor@bgs.org.uk) and for now a cc to me s.slack@bgs.org.uk

**Comment by angievanhegan** [comment] 2018-06-15 13:48
I get the access denied message still. 

![screen shot 2018-06-15 at 08 47 37](https://user-images.githubusercontent.com/3796718/41471298-df74eeb2-7078-11e8-8b11-ee7c4b8468bb.png)

And I see two join buttons...

![screen shot 2018-06-15 at 08 47 48](https://user-images.githubusercontent.com/3796718/41471308-e5630566-7078-11e8-9d93-47e8a4ba62bd.png)

**Comment by angievanhegan** [comment] 2018-06-15 18:09
@pipe-manta Looks good! There are some tweaks to the fields though. The person submitting the details doesn't need all the info. See the list above. 

@StephMSlack What is the registration address? What information are you looking for here?

**Comment by angievanhegan** [comment] 2018-06-18 16:23
@pipe-manta It looks exactly the same. I've cleared the cache too. Am I looking in the wrong place? 
http://bgs-dev.mrmdev.co.uk/events/external-courses/add-an-external-course

**Comment by angievanhegan** [comment] 2018-06-21 19:11
@StephMSlack This is ready for you to review

**Comment by StephMSlack** [comment] 2018-06-22 03:14
@angievanhegan @pipe-manta do we have a login for a non-admin user with an BGS account that I can use to test this process as well and make sure thay can see all the fields etc. Not everyone who is adding an event/course for promotion will be a web admin/admin. thanks

**Comment by StephMSlack** [comment] 2018-06-22 03:17
@pipe-manta the size of the card for the landing page (on events and courses) change depending on what filter is used. The default (soonest) show the cards all the same size, then when a different filter is used the cards re-size to fit the content. The cards should always be the same size.

<img width="1280" alt="screen shot 2018-06-21 at 23 10 05" src="https://user-images.githubusercontent.com/32127102/41756201-3342c9bc-75a9-11e8-9837-92452cae5bcc.png">

<img width="1280" alt="screen shot 2018-06-21 at 23 10 11" src="https://user-images.githubusercontent.com/32127102/41756209-3ee9c7a2-75a9-11e8-8b81-5eeeacc3fbb2.png">

**Comment by angievanhegan** [comment] 2018-06-22 12:49
@pipe-manta A couple more tweaks for you. Thanks

**Comment by russ-manta** [comment] 2018-06-26 13:44
@StephMSlack there's a new account for you on the staging site. I'll send the details over slack

**Comment by russ-manta** [comment] 2018-06-26 13:47
@dilwarhussain can you look at the card height issue after you have looked at all other issues?

**Comment by StephMSlack** [comment] 2018-07-03 22:55
@angievanhegan The courses landing page should not be showing card content and images - it should be the same view as the external events landing page

<img width="813" alt="screen shot 2018-07-03 at 23 54 24" src="https://user-images.githubusercontent.com/32127102/42248243-7d87ad54-7f1c-11e8-9991-be56232b2ded.png">

**Comment by StephMSlack** [comment] 2018-07-03 22:57
@angievanhegan on the submit a course form, the card content information should not be visible
(logged in with an editor account)
<img width="935" alt="screen shot 2018-07-03 at 23 56 38" src="https://user-images.githubusercontent.com/32127102/42248318-dcea5364-7f1c-11e8-963f-ea3f848b591b.png">

**Comment by StephMSlack** [comment] 2018-07-12 10:50
@russ-manta Same issue as #263 where the event start date is defaulting to the current date on publication. Also, the time should not be a required field.

Should get an email confirming that the course has been published and the URL

**Comment by russ-manta** [comment] 2018-07-24 09:34
@StephMSlack I can't replicate the event start date defaulting to the current date on publication. Is this if you create a new revision of the event when publishing?
For the time. The time is not currently shown when viewing an external event - does it need to be (if a time is added)?

**Comment by StephMSlack** [comment] 2018-07-25 12:42
@russ-manta we don't need a time for the courses.
I'll create another test course and see if I am accidentally creating revisions.
Thanks!

**Comment by StephMSlack** [comment] 2018-08-08 11:49
@russ-manta @angievanhegan - the payment for the courses is still pointing to the development site

---------- Forwarded message ---------
From: British Geriatric Society <editor@bgs.org.uk>
Date: Wed, Aug 8, 2018 at 12:46 PM
Subject: Your paid content submission
To: <stephtestbgs2@gmail.com>


Your content has now been reviewed and will be published once payment has been received.

Please proceed to the payment form to make your payment:

http://bgs-staging.mrmdev2.co.uk/civicrm/contribute/transact?reset=1&id=4

If you have any questions please contact editor@bgs.org.uk.

Kind regards
BGS


If you have any questions please contact editor@bgs.org.uk.

Kind regards
BGS

**Comment by russ-manta** [comment] 2018-08-08 11:58
@StephMSlack this one should be fixed now

**Comment by StephMSlack** [comment] 2018-08-08 14:55
thanks @russ-manta 

I am having the same issue here as I have on the external event page. 

The user is filling in the information and the date and pressing save.
When as an admin I go to view the page, the event date has changed to the date and time the user presses save, not the date they added initially.

Form on the website prior to submission
![screen shot 2018-08-08 at 15 00 27](https://user-images.githubusercontent.com/32127102/43845246-74092960-9b23-11e8-8f44-fd15e4b4d1da.png)

Form in drupal after submission
![screen shot 2018-08-08 at 15 01 23](https://user-images.githubusercontent.com/32127102/43845268-7f39c5e2-9b23-11e8-982c-de9d02ecb26f.png)

**Comment by russ-manta** [comment] 2018-08-08 15:47
@StephMSlack this is now fixed

**Comment by russ-manta** [comment] 2018-08-08 15:49
@StephMSlack do you need a start time for these courses or just the date? The problem is that when the person submits the course they don't get the chance to submit a time at the moment (although it is required) so the new date they have selected never saves.  We can fix either by removing the time altogether (if not required) or making sure the time field shows to the person adding the course.

**Comment by StephMSlack** [comment] 2018-08-08 15:56
@russ-manta for courses, just the start date, we can remove the time entirely.

This issue is also happening for the external events submission page.

**Comment by russ-manta** [comment] 2018-08-08 15:57
@StephMSlack ok great, fixed!

**Comment by StephMSlack** [comment] 2018-08-09 14:08
@russ Great - the course submission issue is now fixed.

@angievanhegan @russ-manta could the time also be removed from the external event end date? It has been removed from the start date but not the end date, so the end date is still being overwritten (linked to #263)

![screen shot 2018-08-09 at 15 05 39](https://user-images.githubusercontent.com/32127102/43904180-f68ba8aa-9be5-11e8-8072-c6196cd7282d.png)

**Comment by russ-manta** [comment] 2018-08-09 14:09
@StephMSlack done

**Comment by StephMSlack** [comment] 2018-08-09 14:13
thanks @russ-manta 
@angievanhegan this is good to close

**Closed** 2018-08-10 15:32 UTC
Labels: - Build, - Styling, For go live, Project
